package lego

const (
	// HTTP配置-固定常量
	K_GGF_CONFIG_HTTP_SECTION = "HTTP"
	K_GGF_CONFIG_HTTP_DOMAIN  = "DOMAIN"
	K_GGF_CONFIG_HTTP_PORT    = "PORT"
	// 代码配置-固定常量
	K_GGF_CONFIG_CODE_SECTION         = "CODE"
	K_GGF_CONFIG_CODE_PROJNAME        = "PRJNAME"
	K_GGF_CONFIG_CODE_PRJPREX         = "PRJPREX"
	K_GGF_CONFIG_CODE_TOKEN_SECRETKEY = "TOKEN_SECRETKEY"
	K_GGF_CONFIG_CODE_REQ_SIGNKEY     = "REQ_SIGNKEY"
	// 数据库配置
	K_GGF_CONFIG_DB_SECTION = "DATABASE"
	K_GGF_CONFIG_DB_MASTER  = "MASTER_DB"
)
